### ISSUE TITLE
How to change maximum window size?

### ISSUE THREAD

**Issue by gqchishti** [sussypotato/My_XFCE_dotties#12]
Can you please point me to right direction on how to configure the maximum size for the maximized windows?

I want it to use full space to the left, atm by using linuxscoop video configs, it's not using that.

Thanks.

**Comment by ItsTerm1n4l** [comment]
Here you go   
https://wiki.xfce.org/tips#use_the_desktop_margin   
this shows how to set the desktop margins setting in xfce.

**Comment by gqchishti** [comment]
Thanks. 

settings manager
 - workspace margins
