### ISSUE TITLE
xfce4 panel config

### ISSUE THREAD

**Issue by zanderp** [sussypotato/My_XFCE_dotties#13]
Can you provide any documentation on how to achieve the xfce4 panel configuration?

**Comment by mehedirm6244** [comment]
Use GTK debugger to find the IDs of your panel items, then change the hardcoded IDs to your ones in `~/.config/gtk-3.0/gtk.css` 
You can call GTK debugger like this:
`GTK_DEBUG=interactive xfce4-panel`
