### ISSUE TITLE
how to setup this config ?

### ISSUE THREAD

**Issue by ERFouX** [sussypotato/My_XFCE_dotties#14]
I've installed all the packages I thought I needed and redone all the configs - but I don't know why I can't have your desktop.

**Comment by ItsTerm1n4l** [comment]
what isn't working for you? - maybe you could post a screenshot?

**Comment by ERFouX** [comment]
![Screenshot_2024-06-24_12-45-39](https://github.com/mehedirm6244/Miserable_Xfce/assets/138167877/e60c812d-dd5a-4f92-9fd7-22ca140b314e)

Windows Control - Panel - Icons & .. None are placed correctly

**Comment by ERFouX** [comment]
Maybe I didn't install all the dependencies correctly?
Can you give me a list of dependencies?

**Comment by mehedirm6244** [comment]
There are some stuff working under the hood. You need to modify `gtk.css` and probably another file or two according to your needs. Directly copy/pasting probably won't work with most of the Xfce components
