### ISSUE TITLE
eww stuff,install

### ISSUE THREAD

**Issue by mrlinuxdude** [sussypotato/My_XFCE_dotties#9]
Hi i love your theme so beautiful. i was wondering whats all the eww stuff that needs to be installed i didn't see folder /home dir. also if you can list out the packages that need to be installed so i can know the names of them. Thank you

**Comment by mehedirm6244** [comment]
I haven't pushed my eww configs to the repo yet as I have more to do with the configs. Thanks for your suggestion about listing necessary packages, it'll be contained in the (somewhat) installation tutorial for this rice

**Comment by mrlinuxdude** [comment]
Awesome Thanks.
